apiVersion: v1
kind: Service
metadata:
  name: webapp-color-wl10-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webapp-color-wl10
  type: NodePort
